server:
  port: 8082

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:mysql://localhost:3307/app_target
    username: app_target
    password: app_target1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    initialization-mode: always

app:
  sharding:
    shard-count: 2
    targets:
      shard0:
        url: jdbc:mysql://localhost:3307/app_target
        username: app_target
        password: app_target1234
        driver-class-name: com.mysql.cj.jdbc.Driver
      shard1:
        url: jdbc:mysql://localhost:3309/app_target
        username: app_target
        password: app_target1234
        driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    topics:
      user-registered: outbox.event.user

logging:
  level:
    com.example.kafka.notificationservice: INFO
