server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://localhost:3306/app
    username: app
    password: app1234
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
  jackson:
    serialization:
      write-dates-as-timestamps: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100

logging:
  level:
    com.example.kafka.userservice: INFO
